### ISSUE TITLE
Waypoints?

### ISSUE THREAD

**Issue by Qavai** [bentasker/PHP-GPX-Ingest#4]
What about?

**Comment by bentasker** [comment]
Could conceivably be added, sure (for reference - relevant part of schema is http://www.topografix.com/gpx/1/1/#type_wptType )

In fact, it should be fairly straightforward to drop in as they'll need processing (at ingest) independently of the trackpoints anyway

I guess you'd then want to be able to do something like

    $gpx->listWaypoints();

To return all included Waypoints, or

   $gpx->getWaypoint($wp-id);

To grab by a numerical identifier. Maybe even be able to retrieve by the name specified in the source GPX?

    $gpx->getWaypointByName('foo');

Probably also worth adding something to the JSON metadata to indicate whether there are any waypoints included.

**Comment by Qavai** [comment]
yes, just all list needed

    </trkseg>
  </trk>
  <wpt lat="56.067023" lon="44.4161744">
    <time>2015-07-04T14:33:54Z</time>
    <name>tree</name>
  </wpt>

**Comment by Qavai** [comment]
?

**Comment by bentasker** [comment]
Give the latest version a try, there are three new methods in the class

    public function getWayPointCount()
    public function getWaypoints()
    public function getWaypoint((int)$id)


The easiest way would be to call `getWayPoints` and iterate through the array. Structure of each waypoint is as follows

stdClass Object
	(
	    [name] => Position 1
	    [description] => 
	    [comment] => 
	    [position] => stdClass Object
		(
		    [lat] => 54.9328621088893
		    [lon] => 9.860624216140083
		    [ele] => 0.0
		    [geoidheight] => 
		)

	    [meta] => stdClass Object
		(
		    [time] => 
		    [magvar] => 
		    [source] => 
		    [link] => 
		    [symbol] => 
		    [type] => 
		    [GPS] => stdClass Object
		        (
		            [fix] => 
		            [sat] => 
		            [hdop] => 
		            [vdop] => 
		            [pdop] => 
		            [ageofdgpsdata] => 
		            [dgpsid] => 
		        )

		)

	)

If a property is null then it wasn't present in the source GPX file.

There's more info at http://projects.bentasker.co.uk/jira_projects/browse/GPXIN-24.html and https://www.bentasker.co.uk/documentation/development-programming/222-php-gpx-ingest#waypoints

**Comment by Qavai** [comment]
it's working, thanks
