### ISSUE TITLE
gpx file with many TRK?

### ISSUE THREAD

**Issue by Qavai** [bentasker/PHP-GPX-Ingest#5]
i have file with many trk in one gpx-file...

but your script work only with LAST trk-section in xml...

you could introduce support for these files?

thanks

[20130518.gpx.zip](https://github.com/bentasker/PHP-GPX-Ingest/files/129048/20130518.gpx.zip)

**Comment by bentasker** [comment]
Nice catch - that's a bug.

The script is supposed to support multiple tracks, however, whilst it iterates over them it fails to increase the numeric key used for that track (or within the codebase - journey) and so essentially overwrites the previously processed tracks.

Variable is defined here - https://github.com/bentasker/PHP-GPX-Ingest/blob/master/GPXIngest.class.php#L232
Used here - https://github.com/bentasker/PHP-GPX-Ingest/blob/master/GPXIngest.class.php#L243

But never incremented

**Comment by bentasker** [comment]
Give it a try with the newest version (sorry haven't got time to set a full test running) - it should now work

**Comment by Qavai** [comment]
thanks

**Comment by Qavai** [comment]
new version working same. 

one track only i see

**Comment by bentasker** [comment]
Give the latest version a try - I missed a variable when changing the name to something more meaningful. I can see multiple tracks now

~# cat test.php
	<?php
	include 'GPXIngest.class.php';
	$gpx = new GPXIngest();
	$gpx->loadFile('20130518.gpx');
	$gpx->ingest();

	print_r($gpx->getTrackIDs());
	~# php test.php
	Array
	(
	    [0] => journey0
	    [1] => journey1
	    [2] => journey2
	    [3] => journey3
	    [4] => journey4
	    [5] => journey5
	    [6] => journey6
	    [7] => journey7
	    [8] => journey8
	    [9] => journey9
	    [10] => journey10
	    [11] => journey11
	    [12] => journey12
	    [13] => journey13
	    [14] => journey14
	    [15] => journey15
	)

**Comment by Qavai** [comment]
yes, now is good

thanks

**Comment by bentasker** [comment]
Awesome, closing this and http://projects.bentasker.co.uk/jira_projects/browse/GPXIN-25.html off
