### ISSUE TITLE
Consecutive points with same timestamp → div by zero

### ISSUE THREAD

**Issue by fbonzon** [bentasker/PHP-GPX-Ingest#6]
Consider a GPX file with these four points:

    <trkpt lat="46.585705" lon="6.604863"><ele>603.2</ele><time>2016-02-15T06:34:26Z</time></trkpt>
    <trkpt lat="46.585689" lon="6.604812"><ele>603.2</ele><time>2016-02-15T06:34:27Z</time></trkpt>
    <trkpt lat="46.585658" lon="6.604792"><ele>603.2</ele><time>2016-02-15T06:34:27Z</time></trkpt>
    <trkpt lat="46.585623" lon="6.604806"><ele>603.2</ele><time>2016-02-15T06:34:28Z</time></trkpt>

Lines 2 and 3 have the same timestamp. Different positions though.

PHP-GPX-Ingest currently fails on such input with:

    Warning: Division by zero in GPXIngest->calculateAcceleration() (line 597 of … GPXIngest.class.php).

Before possibly fixing GPXIngest code, I'd like to know: Do you know if it is valid according to the GPX spec to have 2 points with same timestamp?

**Comment by bentasker** [comment]
Hi

Yes having two entries with the same timestamp is possible, though should be unlikely. Most trackers check position at specific intervals (say 2s) so you wouldn't see it - but as far as I know it'd still be a valid GPX, certainly worth fixing if you want to put a pull together.

Ben

**Comment by fbonzon** [comment]
Output of GPS trackers is the prime example of a GPX file. These will indeed unlikely show this problem.

We see other uses too, for planning purposes, such as the path from driving directions. A GPX file generated in such scenario may include no timestamps, or estimated timestamps based on estimated speed. The latter is my use case in this bug.

I'll prepare a PR.

**Comment by fbonzon** [comment]
Also noticed while working on this bug that a GPX file with no timestamps at all would generate more errors:

```
Warning: max(): Array must contain at least one element in …/GPXIngest.class.php on line 549
Warning: max(): Array must contain at least one element in …/GPXIngest.class.php on line 550
Warning: min(): Array must contain at least one element in …/GPXIngest.class.php on line 551
Warning: min(): Array must contain at least one element in …/GPXIngest.class.php on line 552
Warning: Division by zero in …/GPXIngest.class.php on line 553
Warning: Division by zero in …/GPXIngest.class.php on line 554
```

Fixed in the PR.
