### ISSUE TITLE
min and max, lat and lon?

### ISSUE THREAD

**Issue by Qavai** [bentasker/PHP-GPX-Ingest#7]
Can you provide in stats these fields?

**Comment by bentasker** [comment]
What's your use-case?

Are you interested in the max/min as a pair or independently?

I.e. do you simply want a property showing the maximum latitude seen, one for the maximum longitude and then the same for min, or do you want the actual co-ordinates (so a lat/lon in each of those properties)

Either way, should be simple enough to implement, yes. Raised as GPXIN-26

**Comment by Qavai** [comment]
i need bounds 

square bounds for one track, for all file, for one segment

**Comment by bentasker** [comment]
OK that makes sense, should be reasonably straightforward to implement

**Comment by bentasker** [comment]
Give the latest version a try, there are now bounds at each level of the heirachy:

    gpx->getJourneyStats()
    stdClass Object
    (
        [trackpoints] => 778
        [recordedDuration] => 7556
        [segments] => 16
        [tracks] => 16
        [maxacceleration] => 0
        [maxdeceleration] => 0
        [minacceleration] => 0
        [mindeceleration] => 0
        [avgacceleration] => 0
        [avgdeceleration] => 0
        [speedUoM] => Array
            (
            )
    
        [timeMoving] => 0
        [timeStationary] => 0
        [timeAccelerating] => 0
        [timeDecelerating] => 0
        [distanceTravelled] => 0
        [bounds] => stdClass Object
            (
                [Lat] => stdClass Object
                    (
                        [min] => 56.114105
                        [max] => 56.179494
                    )
    
                [Lon] => stdClass Object
                    (
                        [min] => 43.346461
                        [max] => 43.522420
                    )
    
            )
    
        [start] => 1368860043
        [end] => 1368888867
    )

**Comment by Qavai** [comment]
it working, thanks!
