### ISSUE TITLE
where stat fields?

### ISSUE THREAD

**Issue by Qavai** [bentasker/PHP-GPX-Ingest#9]
i dont see these fields in stat

[maxSpeed] => 78
    [minSpeed] => 0
    [modalSpeed] => 68
    [avgspeed] => 55.83

**Comment by bentasker** [comment]
The value that appears most frequently, so if we had the following speeds

1,4,3,1,4,1,6,5,1,2

We'd have the following averages

Mean: 2.8
Mode: 1
Median: 3.5
Range: 5
